language: java

branches:
  except:
    - /^tmp-?.*/

jdk:
  - oraclejdk11
  - oraclejdk13
  - openjdk8
  - openjdk11
  - openjdk13

script:
  - ./gradlew check assembleJavadoc

stages:
  - test
  - mutation-test

jobs:
  include:
    - stage: mutation-test
      jdk: oraclejdk11
      script: ./gradlew pitest coveralls

      # Workaround to TLS issues in JDK 11, see https://github.com/kt3k/coveralls-gradle-plugin/issues/85
      after_success: curl -F 'json_file=@build/coveralls/report.json' 'https://coveralls.io/api/v1/jobs'
